<a href="https://colab.research.google.com/github/prachi397/LetsUpgrade_Data-Science/blob/main/DataScience_AssignmentDay_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question-1**

In [ ]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


**Question-2**

In [ ]:
import numpy as np
l1 = []
for i in range(0, 5): 
    n = int(input("enter the elements of first list: "))
    l1.append(n) # adding the element 
    
l2 = []
for i in range(0, 5): 
    n = int(input("enter the elements of second list: ")) 
    l2.append(n)
print("first list is:",l1)
print("second list is:",l2)
arr1 = np.array(l1)
arr2 = np.array(l2)
print(arr1)
print(arr2)
arr = np.concatenate((arr1,arr2))
print(arr)
print("first sorted array is:",np.sort(arr1))
print("second sorted array is:",np.sort(arr2)

enter the elements of first list: 1
enter the elements of first list: 6
enter the elements of first list: 5
enter the elements of first list: 4
enter the elements of first list: 3
enter the elements of second list: 9
enter the elements of second list: 6
enter the elements of second list: 8
enter the elements of second list: 3
enter the elements of second list: 2
first list is: [1, 6, 5, 4, 3]
second list is: [9, 6, 8, 3, 2]
[1 6 5 4 3]
[9 6 8 3 2]
[1 6 5 4 3 9 6 8 3 2]
first sorted array is: [1 3 4 5 6]
second sorted array is: [2 3 6 8 9]


**Question-3**

In [ ]:
import numpy as np
arr = np.array([[13,16,31],[11,18,20]])
print("number of dimensions is:", arr.ndim)
print("sizee of array is:", arr.size)

number of dimensions is: 2
sizee of array is: 6


**Question-4**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("1-D array is: ", arr)
arr2 = np.reshape(arr,(2,4))
print("array after converting 2-D array is: ",arr2)


1-D array is:  [1 2 3 4 5 6 7 8]
array after converting 2-D array is:  [[1 2 3 4]
 [5 6 7 8]]


**Question-5**

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
print(np.vstack(arr1))
print(np.vstack(arr2))
print(np.hstack(arr1))
print(np.hstack(arr2))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


**Question-6**

In [ ]:
import numpy as np
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])
unique, counts = np.unique(arr_1, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)